export const customStyleProps = {
  color: {
    property: 'color',
    scale: 'textColors',
  },
  cursor: true,
  outline: true,
  transition: true,
  textDecoration: true,
  textTransform: true,
  whiteSpace: true,
  wordBreak: true,
  wordWrap: true,
  fontVariantNumeric: true,
  textOverflow: true,
  overflowWrap: true,
  listStyleType: true,
  listStylePosition: true,
  listStyleImage: true,
};
