import * as PropTypes from 'prop-types';
import {
  isFontFamilyTokenProp,
  isFontSizeTokenProp,
  isFontWeightTokenProp,
  isLineHeightTokenProp,
  isSpaceTokenProp,
  isTextColorTokenProp,
  ResponsiveProp,
} from '@twilio-paste/style-props';

export const TextPropTypes = {
  as: PropTypes.string as any,
  display: ResponsiveProp(PropTypes.string),
  cursor: ResponsiveProp(PropTypes.string),
  content: ResponsiveProp(PropTypes.string),
  fontFamily: isFontFamilyTokenProp,
  fontSize: isFontSizeTokenProp,
  fontStyle: ResponsiveProp(PropTypes.string),
  fontWeight: isFontWeightTokenProp,
  lineHeight: isLineHeightTokenProp,
  letterSpacing: ResponsiveProp(PropTypes.string),
  margin: isSpaceTokenProp,
  marginTop: isSpaceTokenProp,
  marginRight: isSpaceTokenProp,
  marginBottom: isSpaceTokenProp,
  marginLeft: isSpaceTokenProp,
  padding: isSpaceTokenProp,
  paddingTop: isSpaceTokenProp,
  paddingRight: isSpaceTokenProp,
  paddingBottom: isSpaceTokenProp,
  paddingLeft: isSpaceTokenProp,
  overflow: ResponsiveProp(PropTypes.string),
  overflowX: ResponsiveProp(PropTypes.string),
  overflowY: ResponsiveProp(PropTypes.string),
  textAlign: ResponsiveProp(PropTypes.string),
  color: isTextColorTokenProp,
  textDecoration: ResponsiveProp(PropTypes.string),
  textOverflow: ResponsiveProp(PropTypes.string),
  verticalAlign: ResponsiveProp(PropTypes.string),
  whiteSpace: ResponsiveProp(PropTypes.string),
};
