
import * as React from 'react';
import {Text} from '@twilio-paste/text';
import {Grid, StoryIcon} from './__StoryStyles';

import {AccountProfileIcon} from './src/react/AccountProfileIcon';
import {AddOnsIcon} from './src/react/AddOnsIcon';
import {AlertTriggersIcon} from './src/react/AlertTriggersIcon';
import {ApiExplorerIcon} from './src/react/ApiExplorerIcon';
import {ApiKeysIcon} from './src/react/ApiKeysIcon';
import {ArrowRightIcon} from './src/react/ArrowRightIcon';
import {ArrowShaftDownIcon} from './src/react/ArrowShaftDownIcon';
import {ArrowShaftLeftIcon} from './src/react/ArrowShaftLeftIcon';
import {ArrowShaftRightIcon} from './src/react/ArrowShaftRightIcon';
import {ArrowShaftUpIcon} from './src/react/ArrowShaftUpIcon';
import {AssetsIcon} from './src/react/AssetsIcon';
import {AuditEventsIcon} from './src/react/AuditEventsIcon';
import {AuthyIcon} from './src/react/AuthyIcon';
import {AutopilotIcon} from './src/react/AutopilotIcon';
import {BackIcon} from './src/react/BackIcon';
import {BarChartIcon} from './src/react/BarChartIcon';
import {BillingIcon} from './src/react/BillingIcon';
import {BuildIcon} from './src/react/BuildIcon';
import {ChannelsIcon} from './src/react/ChannelsIcon';
import {CheckboxCheckedIcon} from './src/react/CheckboxCheckedIcon';
import {CheckboxMultiIcon} from './src/react/CheckboxMultiIcon';
import {CheckboxUncheckedIcon} from './src/react/CheckboxUncheckedIcon';
import {ClockRegularIcon} from './src/react/ClockRegularIcon';
import {CloseIcon} from './src/react/CloseIcon';
import {CollapseIcon} from './src/react/CollapseIcon';
import {CollapseMenuIcon} from './src/react/CollapseMenuIcon';
import {CollapsedIcon} from './src/react/CollapsedIcon';
import {CommunityIcon} from './src/react/CommunityIcon';
import {ConnectAppsIcon} from './src/react/ConnectAppsIcon';
import {ConnectedDevicesIcon} from './src/react/ConnectedDevicesIcon';
import {ConsoleDashIcon} from './src/react/ConsoleDashIcon';
import {CopyIcon} from './src/react/CopyIcon';
import {DebuggerIcon} from './src/react/DebuggerIcon';
import {DebuggerOldIcon} from './src/react/DebuggerOldIcon';
import {DevToolsIcon} from './src/react/DevToolsIcon';
import {DoNotIcon} from './src/react/DoNotIcon';
import {DocsIcon} from './src/react/DocsIcon';
import {DownloadIcon} from './src/react/DownloadIcon';
import {DropdownIcon} from './src/react/DropdownIcon';
import {EmailIcon} from './src/react/EmailIcon';
import {ExclamationCircleIcon} from './src/react/ExclamationCircleIcon';
import {ExpandIcon} from './src/react/ExpandIcon';
import {ExpandMenuIcon} from './src/react/ExpandMenuIcon';
import {ExternalLinkIcon} from './src/react/ExternalLinkIcon';
import {FaxEnabledIcon} from './src/react/FaxEnabledIcon';
import {FaxIcon} from './src/react/FaxIcon';
import {FilterIcon} from './src/react/FilterIcon';
import {FlexIcon} from './src/react/FlexIcon';
import {GoArrowIcon} from './src/react/GoArrowIcon';
import {HelpBookIcon} from './src/react/HelpBookIcon';
import {HelpIcon} from './src/react/HelpIcon';
import {HideIcon} from './src/react/HideIcon';
import {HomeIcon} from './src/react/HomeIcon';
import {InfoIcon} from './src/react/InfoIcon';
import {InformationIcon} from './src/react/InformationIcon';
import {InspirationIcon} from './src/react/InspirationIcon';
import {InterconnectIcon} from './src/react/InterconnectIcon';
import {IpMessagingIcon} from './src/react/IpMessagingIcon';
import {KeyboardIcon} from './src/react/KeyboardIcon';
import {LearnIcon} from './src/react/LearnIcon';
import {LineChartIcon} from './src/react/LineChartIcon';
import {LogoIcon} from './src/react/LogoIcon';
import {LookupIcon} from './src/react/LookupIcon';
import {MessagingIcon} from './src/react/MessagingIcon';
import {MmsEnabledIcon} from './src/react/MmsEnabledIcon';
import {MoreIcon} from './src/react/MoreIcon';
import {MultiFactorAuthenticationIcon} from './src/react/MultiFactorAuthenticationIcon';
import {NotifyIcon} from './src/react/NotifyIcon';
import {OffIcon} from './src/react/OffIcon';
import {OnIcon} from './src/react/OnIcon';
import {PartnersIcon} from './src/react/PartnersIcon';
import {PauseFlatIcon} from './src/react/PauseFlatIcon';
import {PauseIcon} from './src/react/PauseIcon';
import {PencilIcon} from './src/react/PencilIcon';
import {PhoneNumbersIcon} from './src/react/PhoneNumbersIcon';
import {PhoneVerificationIcon} from './src/react/PhoneVerificationIcon';
import {PieChartIcon} from './src/react/PieChartIcon';
import {PlayFlatIcon} from './src/react/PlayFlatIcon';
import {PlayIcon} from './src/react/PlayIcon';
import {PluginIcon} from './src/react/PluginIcon';
import {PlusButtonIcon} from './src/react/PlusButtonIcon';
import {ProductsIcon} from './src/react/ProductsIcon';
import {ProxyIcon} from './src/react/ProxyIcon';
import {QuestionIcon} from './src/react/QuestionIcon';
import {ResetIcon} from './src/react/ResetIcon';
import {RuntimeIcon} from './src/react/RuntimeIcon';
import {SearchIcon} from './src/react/SearchIcon';
import {SettingsIcon} from './src/react/SettingsIcon';
import {SipTrunkingIcon} from './src/react/SipTrunkingIcon';
import {SmsEnabledIcon} from './src/react/SmsEnabledIcon';
import {SpinnerIcon} from './src/react/SpinnerIcon';
import {StudioIcon} from './src/react/StudioIcon';
import {SuccessIcon} from './src/react/SuccessIcon';
import {SupportIcon} from './src/react/SupportIcon';
import {SupportLifebuoyIcon} from './src/react/SupportLifebuoyIcon';
import {SyncIcon} from './src/react/SyncIcon';
import {TableViewIcon} from './src/react/TableViewIcon';
import {TalkToSalesIcon} from './src/react/TalkToSalesIcon';
import {TaskrouterIcon} from './src/react/TaskrouterIcon';
import {TemplatesIcon} from './src/react/TemplatesIcon';
import {ThumbTackIcon} from './src/react/ThumbTackIcon';
import {TicketHistoryIcon} from './src/react/TicketHistoryIcon';
import {TicketIcon} from './src/react/TicketIcon';
import {TwimlBinsIcon} from './src/react/TwimlBinsIcon';
import {TwoFactorAuthenticationIcon} from './src/react/TwoFactorAuthenticationIcon';
import {UploadIcon} from './src/react/UploadIcon';
import {UsersIcon} from './src/react/UsersIcon';
import {VideoIcon} from './src/react/VideoIcon';
import {ViewIcon} from './src/react/ViewIcon';
import {VoiceEnabledIcon} from './src/react/VoiceEnabledIcon';
import {VoiceIcon} from './src/react/VoiceIcon';
import {WhatsappIcon} from './src/react/WhatsappIcon';
import {WirelessIcon} from './src/react/WirelessIcon';

interface IconProps {
  title?: string;
  decorative?: boolean;
  size?: number;
  color?: string;
}

const IconList: React.FC<IconProps> = props => (
  <Grid>
    <StoryIcon><AccountProfileIcon {...props} /><Text as="p">AccountProfileIcon</Text></StoryIcon>
<StoryIcon><AddOnsIcon {...props} /><Text as="p">AddOnsIcon</Text></StoryIcon>
<StoryIcon><AlertTriggersIcon {...props} /><Text as="p">AlertTriggersIcon</Text></StoryIcon>
<StoryIcon><ApiExplorerIcon {...props} /><Text as="p">ApiExplorerIcon</Text></StoryIcon>
<StoryIcon><ApiKeysIcon {...props} /><Text as="p">ApiKeysIcon</Text></StoryIcon>
<StoryIcon><ArrowRightIcon {...props} /><Text as="p">ArrowRightIcon</Text></StoryIcon>
<StoryIcon><ArrowShaftDownIcon {...props} /><Text as="p">ArrowShaftDownIcon</Text></StoryIcon>
<StoryIcon><ArrowShaftLeftIcon {...props} /><Text as="p">ArrowShaftLeftIcon</Text></StoryIcon>
<StoryIcon><ArrowShaftRightIcon {...props} /><Text as="p">ArrowShaftRightIcon</Text></StoryIcon>
<StoryIcon><ArrowShaftUpIcon {...props} /><Text as="p">ArrowShaftUpIcon</Text></StoryIcon>
<StoryIcon><AssetsIcon {...props} /><Text as="p">AssetsIcon</Text></StoryIcon>
<StoryIcon><AuditEventsIcon {...props} /><Text as="p">AuditEventsIcon</Text></StoryIcon>
<StoryIcon><AuthyIcon {...props} /><Text as="p">AuthyIcon</Text></StoryIcon>
<StoryIcon><AutopilotIcon {...props} /><Text as="p">AutopilotIcon</Text></StoryIcon>
<StoryIcon><BackIcon {...props} /><Text as="p">BackIcon</Text></StoryIcon>
<StoryIcon><BarChartIcon {...props} /><Text as="p">BarChartIcon</Text></StoryIcon>
<StoryIcon><BillingIcon {...props} /><Text as="p">BillingIcon</Text></StoryIcon>
<StoryIcon><BuildIcon {...props} /><Text as="p">BuildIcon</Text></StoryIcon>
<StoryIcon><ChannelsIcon {...props} /><Text as="p">ChannelsIcon</Text></StoryIcon>
<StoryIcon><CheckboxCheckedIcon {...props} /><Text as="p">CheckboxCheckedIcon</Text></StoryIcon>
<StoryIcon><CheckboxMultiIcon {...props} /><Text as="p">CheckboxMultiIcon</Text></StoryIcon>
<StoryIcon><CheckboxUncheckedIcon {...props} /><Text as="p">CheckboxUncheckedIcon</Text></StoryIcon>
<StoryIcon><ClockRegularIcon {...props} /><Text as="p">ClockRegularIcon</Text></StoryIcon>
<StoryIcon><CloseIcon {...props} /><Text as="p">CloseIcon</Text></StoryIcon>
<StoryIcon><CollapseIcon {...props} /><Text as="p">CollapseIcon</Text></StoryIcon>
<StoryIcon><CollapseMenuIcon {...props} /><Text as="p">CollapseMenuIcon</Text></StoryIcon>
<StoryIcon><CollapsedIcon {...props} /><Text as="p">CollapsedIcon</Text></StoryIcon>
<StoryIcon><CommunityIcon {...props} /><Text as="p">CommunityIcon</Text></StoryIcon>
<StoryIcon><ConnectAppsIcon {...props} /><Text as="p">ConnectAppsIcon</Text></StoryIcon>
<StoryIcon><ConnectedDevicesIcon {...props} /><Text as="p">ConnectedDevicesIcon</Text></StoryIcon>
<StoryIcon><ConsoleDashIcon {...props} /><Text as="p">ConsoleDashIcon</Text></StoryIcon>
<StoryIcon><CopyIcon {...props} /><Text as="p">CopyIcon</Text></StoryIcon>
<StoryIcon><DebuggerIcon {...props} /><Text as="p">DebuggerIcon</Text></StoryIcon>
<StoryIcon><DebuggerOldIcon {...props} /><Text as="p">DebuggerOldIcon</Text></StoryIcon>
<StoryIcon><DevToolsIcon {...props} /><Text as="p">DevToolsIcon</Text></StoryIcon>
<StoryIcon><DoNotIcon {...props} /><Text as="p">DoNotIcon</Text></StoryIcon>
<StoryIcon><DocsIcon {...props} /><Text as="p">DocsIcon</Text></StoryIcon>
<StoryIcon><DownloadIcon {...props} /><Text as="p">DownloadIcon</Text></StoryIcon>
<StoryIcon><DropdownIcon {...props} /><Text as="p">DropdownIcon</Text></StoryIcon>
<StoryIcon><EmailIcon {...props} /><Text as="p">EmailIcon</Text></StoryIcon>
<StoryIcon><ExclamationCircleIcon {...props} /><Text as="p">ExclamationCircleIcon</Text></StoryIcon>
<StoryIcon><ExpandIcon {...props} /><Text as="p">ExpandIcon</Text></StoryIcon>
<StoryIcon><ExpandMenuIcon {...props} /><Text as="p">ExpandMenuIcon</Text></StoryIcon>
<StoryIcon><ExternalLinkIcon {...props} /><Text as="p">ExternalLinkIcon</Text></StoryIcon>
<StoryIcon><FaxEnabledIcon {...props} /><Text as="p">FaxEnabledIcon</Text></StoryIcon>
<StoryIcon><FaxIcon {...props} /><Text as="p">FaxIcon</Text></StoryIcon>
<StoryIcon><FilterIcon {...props} /><Text as="p">FilterIcon</Text></StoryIcon>
<StoryIcon><FlexIcon {...props} /><Text as="p">FlexIcon</Text></StoryIcon>
<StoryIcon><GoArrowIcon {...props} /><Text as="p">GoArrowIcon</Text></StoryIcon>
<StoryIcon><HelpBookIcon {...props} /><Text as="p">HelpBookIcon</Text></StoryIcon>
<StoryIcon><HelpIcon {...props} /><Text as="p">HelpIcon</Text></StoryIcon>
<StoryIcon><HideIcon {...props} /><Text as="p">HideIcon</Text></StoryIcon>
<StoryIcon><HomeIcon {...props} /><Text as="p">HomeIcon</Text></StoryIcon>
<StoryIcon><InfoIcon {...props} /><Text as="p">InfoIcon</Text></StoryIcon>
<StoryIcon><InformationIcon {...props} /><Text as="p">InformationIcon</Text></StoryIcon>
<StoryIcon><InspirationIcon {...props} /><Text as="p">InspirationIcon</Text></StoryIcon>
<StoryIcon><InterconnectIcon {...props} /><Text as="p">InterconnectIcon</Text></StoryIcon>
<StoryIcon><IpMessagingIcon {...props} /><Text as="p">IpMessagingIcon</Text></StoryIcon>
<StoryIcon><KeyboardIcon {...props} /><Text as="p">KeyboardIcon</Text></StoryIcon>
<StoryIcon><LearnIcon {...props} /><Text as="p">LearnIcon</Text></StoryIcon>
<StoryIcon><LineChartIcon {...props} /><Text as="p">LineChartIcon</Text></StoryIcon>
<StoryIcon><LogoIcon {...props} /><Text as="p">LogoIcon</Text></StoryIcon>
<StoryIcon><LookupIcon {...props} /><Text as="p">LookupIcon</Text></StoryIcon>
<StoryIcon><MessagingIcon {...props} /><Text as="p">MessagingIcon</Text></StoryIcon>
<StoryIcon><MmsEnabledIcon {...props} /><Text as="p">MmsEnabledIcon</Text></StoryIcon>
<StoryIcon><MoreIcon {...props} /><Text as="p">MoreIcon</Text></StoryIcon>
<StoryIcon><MultiFactorAuthenticationIcon {...props} /><Text as="p">MultiFactorAuthenticationIcon</Text></StoryIcon>
<StoryIcon><NotifyIcon {...props} /><Text as="p">NotifyIcon</Text></StoryIcon>
<StoryIcon><OffIcon {...props} /><Text as="p">OffIcon</Text></StoryIcon>
<StoryIcon><OnIcon {...props} /><Text as="p">OnIcon</Text></StoryIcon>
<StoryIcon><PartnersIcon {...props} /><Text as="p">PartnersIcon</Text></StoryIcon>
<StoryIcon><PauseFlatIcon {...props} /><Text as="p">PauseFlatIcon</Text></StoryIcon>
<StoryIcon><PauseIcon {...props} /><Text as="p">PauseIcon</Text></StoryIcon>
<StoryIcon><PencilIcon {...props} /><Text as="p">PencilIcon</Text></StoryIcon>
<StoryIcon><PhoneNumbersIcon {...props} /><Text as="p">PhoneNumbersIcon</Text></StoryIcon>
<StoryIcon><PhoneVerificationIcon {...props} /><Text as="p">PhoneVerificationIcon</Text></StoryIcon>
<StoryIcon><PieChartIcon {...props} /><Text as="p">PieChartIcon</Text></StoryIcon>
<StoryIcon><PlayFlatIcon {...props} /><Text as="p">PlayFlatIcon</Text></StoryIcon>
<StoryIcon><PlayIcon {...props} /><Text as="p">PlayIcon</Text></StoryIcon>
<StoryIcon><PluginIcon {...props} /><Text as="p">PluginIcon</Text></StoryIcon>
<StoryIcon><PlusButtonIcon {...props} /><Text as="p">PlusButtonIcon</Text></StoryIcon>
<StoryIcon><ProductsIcon {...props} /><Text as="p">ProductsIcon</Text></StoryIcon>
<StoryIcon><ProxyIcon {...props} /><Text as="p">ProxyIcon</Text></StoryIcon>
<StoryIcon><QuestionIcon {...props} /><Text as="p">QuestionIcon</Text></StoryIcon>
<StoryIcon><ResetIcon {...props} /><Text as="p">ResetIcon</Text></StoryIcon>
<StoryIcon><RuntimeIcon {...props} /><Text as="p">RuntimeIcon</Text></StoryIcon>
<StoryIcon><SearchIcon {...props} /><Text as="p">SearchIcon</Text></StoryIcon>
<StoryIcon><SettingsIcon {...props} /><Text as="p">SettingsIcon</Text></StoryIcon>
<StoryIcon><SipTrunkingIcon {...props} /><Text as="p">SipTrunkingIcon</Text></StoryIcon>
<StoryIcon><SmsEnabledIcon {...props} /><Text as="p">SmsEnabledIcon</Text></StoryIcon>
<StoryIcon><SpinnerIcon {...props} /><Text as="p">SpinnerIcon</Text></StoryIcon>
<StoryIcon><StudioIcon {...props} /><Text as="p">StudioIcon</Text></StoryIcon>
<StoryIcon><SuccessIcon {...props} /><Text as="p">SuccessIcon</Text></StoryIcon>
<StoryIcon><SupportIcon {...props} /><Text as="p">SupportIcon</Text></StoryIcon>
<StoryIcon><SupportLifebuoyIcon {...props} /><Text as="p">SupportLifebuoyIcon</Text></StoryIcon>
<StoryIcon><SyncIcon {...props} /><Text as="p">SyncIcon</Text></StoryIcon>
<StoryIcon><TableViewIcon {...props} /><Text as="p">TableViewIcon</Text></StoryIcon>
<StoryIcon><TalkToSalesIcon {...props} /><Text as="p">TalkToSalesIcon</Text></StoryIcon>
<StoryIcon><TaskrouterIcon {...props} /><Text as="p">TaskrouterIcon</Text></StoryIcon>
<StoryIcon><TemplatesIcon {...props} /><Text as="p">TemplatesIcon</Text></StoryIcon>
<StoryIcon><ThumbTackIcon {...props} /><Text as="p">ThumbTackIcon</Text></StoryIcon>
<StoryIcon><TicketHistoryIcon {...props} /><Text as="p">TicketHistoryIcon</Text></StoryIcon>
<StoryIcon><TicketIcon {...props} /><Text as="p">TicketIcon</Text></StoryIcon>
<StoryIcon><TwimlBinsIcon {...props} /><Text as="p">TwimlBinsIcon</Text></StoryIcon>
<StoryIcon><TwoFactorAuthenticationIcon {...props} /><Text as="p">TwoFactorAuthenticationIcon</Text></StoryIcon>
<StoryIcon><UploadIcon {...props} /><Text as="p">UploadIcon</Text></StoryIcon>
<StoryIcon><UsersIcon {...props} /><Text as="p">UsersIcon</Text></StoryIcon>
<StoryIcon><VideoIcon {...props} /><Text as="p">VideoIcon</Text></StoryIcon>
<StoryIcon><ViewIcon {...props} /><Text as="p">ViewIcon</Text></StoryIcon>
<StoryIcon><VoiceEnabledIcon {...props} /><Text as="p">VoiceEnabledIcon</Text></StoryIcon>
<StoryIcon><VoiceIcon {...props} /><Text as="p">VoiceIcon</Text></StoryIcon>
<StoryIcon><WhatsappIcon {...props} /><Text as="p">WhatsappIcon</Text></StoryIcon>
<StoryIcon><WirelessIcon {...props} /><Text as="p">WirelessIcon</Text></StoryIcon>
  </Grid>
);

export {IconList};
