import {
  backgroundColors,
  borderColors,
  borderWidths,
  radii,
  colors,
  fonts,
  fontSizes,
  fontWeights,
  lineHeights,
  boxShadows,
  sizings,
  spacings,
  textColors,
  zIndices,
} from '@twilio-paste/design-tokens';

const breakpoints = [sizings.size40, sizings.size100, sizings.size120];
export const DefaultTheme = {
  shadows: boxShadows,
  backgroundColors,
  borderColors,
  borderWidths,
  radii,
  breakpoints,
  colors,
  fonts,
  fontSizes,
  fontWeights,
  lineHeights,
  widths: sizings,
  maxWidths: sizings,
  minWidths: sizings,
  heights: sizings,
  maxHeights: sizings,
  minHeights: sizings,
  space: spacings,
  textColors,
  zIndices,
};
