import {
  backgroundColors,
  borderColors,
  borderWidths,
  radii,
  colors,
  fonts,
  fontSizes,
  fontWeights,
  lineHeights,
  boxShadows,
  sizings,
  spacings,
  textColors,
  zIndices,
} from '@twilio-paste/design-tokens';

const breakpoints = [sizings.size40, sizings.size100, sizings.size120];
export const DefaultTheme = {
  backgroundColors,
  borderColors,
  borderWidths,
  breakpoints,
  colors,
  fonts,
  fontSizes,
  fontWeights,
  heights: sizings,
  lineHeights,
  maxWidths: sizings,
  minWidths: sizings,
  radii,
  shadows: boxShadows,
  space: spacings,
  textColors,
  widths: sizings,
  zIndices,
};
