# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  job-executor:
    docker:
      - image: circleci/node:10.16.3-browsers
    working_directory: ~/repo

jobs:
  build:
    executor: job-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            - v4-dependencies-
      - run: yarn
      - run: yarn bootstrap
      - save_cache:
          key: v4-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run package builds
          command: yarn build
      - run:
          name: Run type checker
          command: yarn type-check
      - run:
          name: Run eslint
          command: yarn lint
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/packages

  test:
    executor: job-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            - v4-dependencies-
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test

  applitools:
    executor: job-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            - v4-dependencies-
      - attach_workspace:
          at: ~/
      - run:
          name: Run applitools eyes-storybook
          command: yarn test:vrt

  prettier:
    executor: job-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            - v4-dependencies-
      - attach_workspace:
          at: ~/
      - run:
          name: Run prettier
          command: yarn prettier

workflows:
  version: 2
  Build and Test:
    jobs:
      - build
      - test:
          requires:
            - build
      - prettier:
          requires:
            - build
      # applitools must come last
      - applitools:
          requires:
            - prettier
