export type TokenCategory =
  | "background-color"
  | "border-color"
  | "radius"
  | "border-width"
  | "box-shadow"
  | "data-visualization"
  | "font"
  | "font-size"
  | "font-weight"
  | "line-height"
  | "color"
  | "sizing"
  | "spacing"
  | "text-color"
  | "z-index";
