import { TokenCategory } from '../types';

export const pasteTokenAttributes: Record<string, TokenCategory> = {
  margin: 'spacing',
  marginTop: 'spacing',
  marginRight: 'spacing',
  marginBottom: 'spacing',
  marginLeft: 'spacing',
  marginX: 'spacing',
  marginY: 'spacing',
  padding: 'spacing',
  paddingTop: 'spacing',
  paddingRight: 'spacing',
  paddingBottom: 'spacing',
  paddingLeft: 'spacing',
  paddingX: 'spacing',
  paddingY: 'spacing',
  borderRadius: 'radius',
  borderTopLeftRadius: 'radius',
  borderTopRightRadius: 'radius',
  borderBottomRightRadius: 'radius',
  borderBottomLeftRadius: 'radius',
  borderWidth: 'border-width',
  borderTopWidth: 'border-width',
  borderRightWidth: 'border-width',
  borderBottomWidth: 'border-width',
  borderLeftWidth: 'border-width',
  borderColor: 'border-color',
  borderTopColor: 'border-color',
  borderRightColor: 'border-color',
  borderBottomColor: 'border-color',
  borderLeftColor: 'border-color',
  zIndex: 'z-index',
  backgroundColor: 'background-color',
  columnGap: 'spacing',
  rowGap: 'spacing',
  boxShadow: 'box-shadow',
  fontSize: 'font-size',
  fontWeight: 'font-weight',
  lineHeight: 'line-height',
  color: 'text-color',
  size: 'sizing',
};
