import pasteTokens from '.';

export const pasteTokenAttributes: Record<string, keyof typeof pasteTokens> = {
  margin: 'spacings',
  marginTop: 'spacings',
  marginRight: 'spacings',
  marginBottom: 'spacings',
  marginLeft: 'spacings',
  marginX: 'spacings',
  marginY: 'spacings',
  padding: 'spacings',
  paddingTop: 'spacings',
  paddingRight: 'spacings',
  paddingBottom: 'spacings',
  paddingLeft: 'spacings',
  paddingX: 'spacings',
  paddingY: 'spacings',
  borderRadius: 'radii',
  borderTopLeftRadius: 'radii',
  borderTopRightRadius: 'radii',
  borderBottomRightRadius: 'radii',
  borderBottomLeftRadius: 'radii',
  borderWidth: 'borderWidths',
  borderTopWidth: 'borderWidths',
  borderRightWidth: 'borderWidths',
  borderBottomWidth: 'borderWidths',
  borderLeftWidth: 'borderWidths',
  borderColor: 'borderColors',
  borderTopColor: 'borderColors',
  borderRightColor: 'borderColors',
  borderBottomColor: 'borderColors',
  borderLeftColor: 'borderColors',
  zIndex: 'zIndices',
  backgroundColor: 'backgroundColors',
  columnGap: 'spacings',
  rowGap: 'spacings',
  boxshadow: 'boxShadows',
  fontSize: 'fontSizes',
  fontWeight: 'fontWeights',
  lineHeight: 'lineHeights',
  color: 'textColors',
  size: 'sizings',
};
