/**
 * Expected shape of an article's Front Matter.
 *
 * @export
 * @interface ArticleFrontMatter
 */
export interface ArticleFrontMatter {
  author: string;
  avatar: string;
  date: string;
  description: string;
  /**
   * Use this to manually create an article excerpt, when the article is an external linked source.
   *
   * @type {string}
   * @memberof ArticleFrontMatter
   */
  excerpt?: string;
  /**
   * Set an external link when the article is an external linked source.s
   *
   * @type {string}
   * @memberof ArticleFrontMatter
   */
  external_link?: string;
  machineDate: string;
  slug: string;
  status: 'published' | 'draft';
  title: string;
}

/**
 * Shape of an Articles edge coming from gastby
 *
 * @export
 * @interface ArticleNode
 */
export interface ArticleNode {
  /**
   * Excerpt of the article that is generated by the markdown parser.
   *
   * @type {string}
   * @memberof ArticleNode
   */
  excerpt: string;

  /**
   * Front matter object set in the article
   *
   * @type {ArticleFrontMatter}
   * @memberof ArticleNode
   */
  frontmatter: ArticleFrontMatter;
}
