create table "public"."queries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "query_string" character varying,
    "type" text
);


alter table "public"."queries" enable row level security;

alter table "public"."page" enable row level security;

alter table "public"."page_section" enable row level security;

CREATE UNIQUE INDEX queries_pkey ON public.queries USING btree (id);

alter table "public"."queries" add constraint "queries_pkey" PRIMARY KEY using index "queries_pkey";

create policy "Public access"
on "public"."page"
as permissive
for all
to public
using (true)
with check (true);


create policy "Public access"
on "public"."page_section"
as permissive
for all
to public
using (true)
with check (true);


create policy "Enable read access for all"
on "public"."queries"
as permissive
for select
to public
using (true);


create policy "Enable write access for all"
on "public"."queries"
as permissive
for insert
to public
with check (true);



