create table "public"."assistant_threads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "openai_thread_id" character varying,
    "slack_thread_ts" character varying
);


alter table "public"."assistant_threads" enable row level security;

CREATE UNIQUE INDEX assistant_threads_pkey ON public.assistant_threads USING btree (id);

alter table "public"."assistant_threads" add constraint "assistant_threads_pkey" PRIMARY KEY using index "assistant_threads_pkey";

grant delete on table "public"."assistant_threads" to "anon";

grant insert on table "public"."assistant_threads" to "anon";

grant references on table "public"."assistant_threads" to "anon";

grant select on table "public"."assistant_threads" to "anon";

grant trigger on table "public"."assistant_threads" to "anon";

grant truncate on table "public"."assistant_threads" to "anon";

grant update on table "public"."assistant_threads" to "anon";

grant delete on table "public"."assistant_threads" to "authenticated";

grant insert on table "public"."assistant_threads" to "authenticated";

grant references on table "public"."assistant_threads" to "authenticated";

grant select on table "public"."assistant_threads" to "authenticated";

grant trigger on table "public"."assistant_threads" to "authenticated";

grant truncate on table "public"."assistant_threads" to "authenticated";

grant update on table "public"."assistant_threads" to "authenticated";

grant delete on table "public"."assistant_threads" to "service_role";

grant insert on table "public"."assistant_threads" to "service_role";

grant references on table "public"."assistant_threads" to "service_role";

grant select on table "public"."assistant_threads" to "service_role";

grant trigger on table "public"."assistant_threads" to "service_role";

grant truncate on table "public"."assistant_threads" to "service_role";

grant update on table "public"."assistant_threads" to "service_role";

create policy "Public access"
on "public"."assistant_threads"
as permissive
for all
to public
using (true)
with check (true);



