export const BadgeVariants = [
  "neutral",
  "warning",
  "error",
  "success",
  "new",
  "subaccount",
  "decorative10",
  "decorative20",
  "decorative30",
  "decorative40",
  "brand10",
  "brand20",
  "brand30",
  "neutral_counter",
  "error_counter",
  "default",
  "notification_counter",
  // the following variants are outdated but still supported to prevent breaking changes
  "info",
] as const;
