import type {Properties} from 'csstype';
import {type ResponsiveValue} from '@twilio-paste/styling-library';

export type AnimationProperty = Properties['animation'];
export type AppearanceProperty = Properties['appearance'];
export type BoxSizingProperty = Properties['boxSizing'];
export type ClipProperty = Properties['clip']; // 'clip' is deprecated
export type CursorProperty = Properties['cursor'];
export type FloatProperty = Properties['float'];
export type ObjectFitProperty = Properties['objectFit'];
export type ObjectPositionProperty = Properties['objectPosition'];
export type OpacityProperty = Properties['opacity'];
export type OutlineProperty = Properties['outline'];
export type PointerEventsProperty = Properties['pointerEvents'];
export type ResizeProperty = Properties['resize'];
export type TableLayoutProperty = Properties['tableLayout'];
export type TransformOriginProperty = Properties['transformOrigin'];
export type TransformProperty = Properties['transform'];
export type TransitionProperty = Properties['transition'];
export type TransitionDelayProperty = Properties['transitionDelay'];
export type UserSelectProperty = Properties['userSelect'];
export type VisibilityProperty = Properties['visibility'];
export type WillChangeProperty = Properties['willChange'];

export type Animation = ResponsiveValue<AnimationProperty>;
export type Appearance = ResponsiveValue<AppearanceProperty>;
export type BoxSizing = ResponsiveValue<BoxSizingProperty>;
export type Clip = ResponsiveValue<ClipProperty>;
export type Cursor = ResponsiveValue<CursorProperty>;
export type Float = ResponsiveValue<FloatProperty>;
export type ObjectFit = ResponsiveValue<ObjectFitProperty>;
export type ObjectPosition = ResponsiveValue<ObjectPositionProperty>;
export type Opacity = ResponsiveValue<OpacityProperty>;
export type Outline = ResponsiveValue<OutlineProperty>;
export type PointerEvents = ResponsiveValue<PointerEventsProperty>;
export type Resize = ResponsiveValue<ResizeProperty>;
export type TableLayout = ResponsiveValue<TableLayoutProperty>;
export type TransformOrigin = ResponsiveValue<TransformOriginProperty>;
export type Transform = ResponsiveValue<TransformProperty>;
export type Transition = ResponsiveValue<TransitionProperty>;
export type TransitionDelay = ResponsiveValue<TransitionDelayProperty>;
export type UserSelect = ResponsiveValue<UserSelectProperty>;
export type Visibility = ResponsiveValue<VisibilityProperty>;
export type WillChange = ResponsiveValue<WillChangeProperty>;

export type CSSProps = {
  animation?: Animation;
  appearance?: Appearance;
  boxSizing?: BoxSizing;
  clip?: Clip;
  content?: string;
  cursor?: Cursor;
  float?: Float;
  objectFit?: ObjectFit;
  objectPosition?: ObjectPosition;
  opacity?: Opacity;
  outline?: Outline;
  pointerEvents?: PointerEvents;
  resize?: Resize;
  tableLayout?: TableLayout;
  transform?: Transform;
  transformOrigin?: TransformOrigin;
  transition?: Transition;
  transitionDelay?: TransitionDelay;
  userSelect?: UserSelect;
  visibility?: Visibility;
  willChange?: WillChange;
  '-webkit-text-fill-color'?: string;
  '-webkit-opacity'?: string;
};
