name: Discussion auto-responder
on:
  discussion:
    types: [created]
env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  on_discussion_open:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: "v1.x"
      - name: Run Deno script
        run: npm run ci:autorespond -- "${{ github.event.discussion.body }}" "${{ github.event.discussion.node_id }}"
