name: Opened Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-context-labeller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 20.5
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.x

      - name: Assign Author
        uses: technote-space/assign-author@v1

      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        with:
          GITHUB_TOKEN: "${{ secrets.PAT_GH_READ_ORG }}"
          username: "${{ github.actor }}"
          # List of all teams for dsys
          team: "Design Systems PD"

          # ,design-systems,Design Systems Eng,Design Systems Eng Leads

      - name: Debug in group
        run: echo "${{ github.actor }} is team member ${{ steps.teamAffiliation.outputs.isTeamMember }}"

      - name: Auto contribution labeller
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'false' }}
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/opened-pr-contribution-labeler.yml
