name: Opened Pull Request Labeler

on:
  pull_request:
    types: [opened]

jobs:
  pr-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Auto labeller
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/opened-pr-labeler.yml
      - name: Assign Author
        uses: technote-space/assign-author@v1
