name: Opened Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author
        uses: technote-space/assign-author@v1

      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_GH_READ_ORG }}
          username: ${{ github.actor }}
          team: "design-systems-eng,design-systems-pd"

      - name: Debug in group
        run: echo "${{ github.actor }} is team member ${{ steps.teamAffiliation.outputs.isTeamMember }}"

      - name: Auto contribution labeller
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'false' }}
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/opened-pr-contribution-labeler.yml
