name: Track workflow metrics

# Controls when the workflow will run
on:
  workflow_run:
    workflows:
      - "**"
    types:
      - completed
  pull_request:
  push:

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: int128/datadog-actions-metrics@v1
        with:
          # create an API key in https://docs.datadoghq.com/account_management/api-app-keys/
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          collect-job-metrics: true
